version: 0.2
phases:
  # install:
  #   runtime-versions:
  #     python: 3.12
    # commands:
    #   - echo "Installing dependencies..."
    #   - pip install -r requirements.txt -t lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - zip -r ../deployment_package.zip .
      - pwd
      - ls
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name TestLambda --zip-file fileb://deployment_package.zip
      - echo "DONE!!"